export enum QUERY_KEY {
    ARTICLE = 'ARTICLE',
    ARTICLES = 'ARTICLES',
    CATEGORIES = 'categories',
    CATEGORY = 'category',
    CATEGORY_OPTIONS = 'CATEGORY_OPTIONS',
    PRODUCT = 'product',
    PRODUCTS = 'products',
    SETTING = 'SETTING',
    PAGES = 'PAGES',
    PRODUCT_OPTIONS = 'PRODUCT_OPTIONS',
    ARTICLE_OPTIONS = 'ARTICLE_OPTIONS',
}
